# Prepare build environment

* Download https://www.nxp.com/docs/en/supporting-information/android_O8.1.0_1.3.0_8M_docs.tar.gz[`android_O8.1.0_1.3.0_8M_docs.tar.gz`]
* Set up your computer as described in the `android_O8.1.0_1.3.0_8M_docs/Android_User's_Guide.pdf`.

# Clone this repository
[source,console]
mkdir ~/compulab-imx8
git clone https://github.com/compulab-yokneam/imx8.git ~/compulab-imx8
cd ~/compulab-imx8/o8
export C=$(pwd)

# Set up the Android `repo` utility
[source,console]
mkdir ~/bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
export PATH=${PATH}:~/bin

# Deploy the NXP Source Code
[source,console]
tar -C ~/ -xzvf ${C}/NXP/src/imx-o8.1.0_1.3.0_8m.tar.gz
source ~/imx-o8.1.0_1.3.0_8m/imx_android_setup.sh
export A=~/android_build

# Add `CompuLab imx8` board support
## Apply the patches:
* U-boot
[source,console]
git -C ${A}/vendor/nxp-opensource/uboot-imx checkout -b compulab-imx8 2537522
git -C ${A}/vendor/nxp-opensource/uboot-imx am ${C}/vendor/nxp-opensource/uboot-imx/*.patch

* Kernel
[source,console]
git -C ${A}/vendor/nxp-opensource/kernel_imx checkout -b compulab-imx8 7e45d57
git -C ${A}/vendor/nxp-opensource/kernel_imx am ${C}/vendor/nxp-opensource/kernel_imx/*.patch

* Board
[source,console]
git -C ${A}/device/fsl checkout -b compulab-imx8 3327a32
git -C ${A}/device/fsl am ${C}/device/fsl/*.patch

# Create the image
* Set a desire machine configuration
** `export MACHINE=cl-som-imx8`

* Goto `~/myandroid` and issue the sequence:
[source,console]
cd ${A}
source build/envsetup.sh
lunch ${MACHINE}-eng
make -j 8

* Wait for this message:
[source,console]
#### build completed successfully (01:12 (mm:ss)) ####

* Goto the target output directory and generate the image.
[source,console]
cd out/target/product/${MACHINE}
sudo ${C}/tools/create-image

# Create a bootable SD-card
An 7G image gets created at `/tmp` directory with the `/tmp/image-${MACHINE}-7G-$(date +%Y_%m_%d-%H_%M_%S)` name. Create a bootable SD-card this way:
[source,console]
pv /tmp/image-cl-som-imx8-7G-2018_09_12-16_10_50 | sudo dd of=/dev/sdX bs=1M

# Pre-Built Development Image
https://drive.google.com/open?id=1vuhfFb9F58t3i71zXvGekWL7rKglRXEa[cl-som-imx8 Oreo 8 Image]

# Boot from SD-card
* Insert a created SD card into the SD socket `P13` (SB-iMX8 print side).
* Power on the board
* Press and hold `SW5` and `SW6`
* Release `SW5` and then `SW6`

# ADB
The device USB1 configured as a `peripheral` device, that allows connecting the device to a desktop PC using `adb shell`.

How to connect: PC-USB <==> `USB 2.0 Type A ------ USB 2.0 Micro-B 5 Pin` <==> P9-SB-iMX8

# Known issues
## Empty Serial Number
* This `Pre-Built Development Image` has an issue by reporting an empty string as the device serial number.
As a result Windows' desktops can't get connected to the board using `adb shell`.
In order to address this issue apply one of the followed solutions:

### Solution 1
Get connected to the device throught the serial console, then issue:
[source,console]
su
echo 'cl-som-imx8' > /config/usb_gadget/g1/strings/0x409/serialnumber
pkill -9 adbd

### Solution 2
Rebuild the image. The patch https://github.com/compulab-yokneam/imx8/commit/ea00f2a56def567a450f7ce0d2c525042689a2ee[`ea00f2a56def567a450f7ce0d2c525042689a2ee`] fixes the issue.

## WiFi Connection
WiFi scans networks, but can't get connected to.
