# Prepare build environment

* Download https://www.nxp.com/docs/en/supporting-information/android_O8.1.0_1.3.0_8M_docs.tar.gz[`android_O8.1.0_1.3.0_8M_docs.tar.gz`]

* Follow the instructions of the `android_O8.1.0_1.3.0_8M_docs/Android_User's_Guide.pdf` and stop on the step 3.2.
* Set an environment variable `A`
[source,console]
export A=~/android_build

# Clone this repository
[source,console]
mkdir ~/compulab-imx8
git clone https://github.com/compulab-yokneam/imx8.git ~/compulab-imx8
cd ~/compulab-imx8/o8
export C=$(pwd)

# Add `CompuLab imx8` board support
## Apply the patches:
* U-boot
[source,console]
git -C ${A}/vendor/nxp-opensource/uboot-imx checkout -b compulab-imx8 2537522
git -C ${A}/vendor/nxp-opensource/uboot-imx am ${C}/vendor/nxp-opensource/uboot-imx/*.patch

* Kernel
[source,console]
git -C ${A}/vendor/nxp-opensource/kernel_imx checkout -b compulab-imx8 7e45d57
git -C ${A}/vendor/nxp-opensource/kernel_imx am ${C}/vendor/nxp-opensource/kernel_imx/*.patch

* Board
[source,console]
git -C ${A}/device/fsl checkout -b compulab-imx8 3327a32
git -C ${A}/device/fsl am ${C}/device/fsl/*.patch

# Create the image
* Set a desire machine configuration
** `export MACHINE=cl-som-imx8`

* Goto `~/myandroid` and issue the sequence:
[source,console]
cd ${A}
source build/envsetup.sh
lunch ${MACHINE}-eng
make -j 8

* Wait for this message:
[source,console]
#### build completed successfully (01:12 (mm:ss)) ####

* Goto the target output directory and generate the image.
[source,console]
cd out/target/product/${MACHINE}
sudo ${C}/tools/create-image

# Create a bootable SD-card
An 7G image gets created at `/tmp` directory with the `/tmp/image-${MACHINE}-7G-$(date +%Y_%m_%d-%H_%M_%S)` name. Create a bootable SD-card this way:
[source,console]
pv /tmp/image-cl-som-imx8-7G-2018_09_12-16_10_50 | sudo dd of=/dev/sdX bs=1M

# Pre-Built Development Image
https://drive.google.com/open?id=1vuhfFb9F58t3i71zXvGekWL7rKglRXEa[cl-som-imx8 Oreo 8 Image]

# ADB
The device USB1 configured as a `peripheral` device, that allows connecting the device to a desktop PC using `adb shell`.

How to connect: PC-USB <==> `USB 2.0 Type A ------ USB 2.0 Micro-B 5 Pin` <==> P9-SB-iMX8

# Known issues
* This `Pre-Built Development Image` has an issue by reporting an empty string as the device serial number.
As a result the board can't get connected a desktop PC using `adb shell`.
In order to address this issue:
** Get connected to the device throught the serial console, then issue:
[source,console]
su
echo 'cl-som-imx8' > /config/usb_gadget/g1/strings/0x409/serialnumber
pkill -9 adbd
** Rebuild the image. The latest patch fixes the issue.
