# CompuLab Android Pie 9

* Set up the Android `repo` utility
[source,console]
mkdir ~/bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
export PATH=${PATH}:~/bin

# NXP Resources
* i.MX Android proprietary Source Code: https://www.nxp.com/webapp/sps/download/license.jsp?colCode=P9.0.0_2.1.0_AUTO_GA_SOURCE&appType=file1&DOWNLOAD_ID=null[imx-p9.0.0_2.1.0-auto-ga.tar.gz]

* Documentation: https://www.nxp.com/docs/en/supporting-information/android_p9.0.0_2.1.0-auto-ga_docs.zip[android_p9.0.0_2.1.0-auto-ga_docs.zip]

* Create a bsp directory:
[source,console]
mkdir -p /path/to/bsp
export BSP=/path/to/bsp

* Untar the Android source archive:
[source,console]
tar -C ${BSP} -xf /path/to/imx-p9.0.0_2.1.0-auto-ga.tar.gz

* Setup Source:
[source,console]
source ${BSP}/imx-p9.0.0_2.1.0-auto-ga/imx_android_setup.sh
export A=${BSP}/android_build

* Follow the instructions of the `${BSP}/imx-p9.0.0_2.1.0-auto-ga/README` and make sure that the build environment is ready

IMPORTANT: It is up to developers to make sure that NXP procedure works and an NXP example image can be created.
Refer to the `imx-p9.0.0_2.1.0-auto-ga/README` for details.

# CompuLab Sources
* Clone this repository
[source,console]
mkdir ${BSP}/compulab-imx8
git clone --single-branch --branch p9.0.0_2.1.0-auto-ga https://github.com/compulab-yokneam/imx8.git ${BSP}/compulab-imx8
export C=${BSP}/compulab-imx8

# Apply the patches:
* U-boot
[source,console]
git -C ${A}/vendor/nxp-opensource/uboot-imx checkout -b compulab-imx8 p9.0.0_2.1.0-auto-ga
git -C ${A}/vendor/nxp-opensource/uboot-imx am ${C}/vendor/nxp-opensource/uboot-imx/*.patch

* Kernel
[source,console]
git -C ${A}/vendor/nxp-opensource/kernel_imx checkout -b compulab-imx8 p9.0.0_2.1.0-auto-ga
git -C ${A}/vendor/nxp-opensource/kernel_imx am ${C}/vendor/nxp-opensource/kernel_imx/*.patch

* Alsa
[source,console]
git -C ${A}/vendor/nxp-opensource/imx/alsa checkout -b compulab-imx8 p9.0.0_2.1.0-auto-ga
git -C ${A}/vendor/nxp-opensource/imx/alsa am ${C}/vendor/nxp-opensource/imx/alsa/*.patch

* Bluetooth
[source,console]
git -C ${A}/hardware/broadcom/libbt checkout -b compulab-imx8 p9.0.0_2.1.0-auto-ga
git -C ${A}/hardware/broadcom/libbt am ${C}/hardware/broadcom/libbt/*.patch

* Board
[source,console]
git -C ${A}/device/fsl checkout -b compulab-imx8 p9.0.0_2.1.0-auto-ga
git -C ${A}/device/fsl am ${C}/device/fsl/imx8m/*.patch

# Create the image
Set a desire machine configuration:

* `ucm-imx8m-mini`
** `export MACHINE=ucm_imx8m_mini SOC=imx8mm`

IMPORTANT: Underscore in the `MACHINE` name is not a typo.

* Goto Android build directory and issue:
[source,console]
cd ${A}
source build/envsetup.sh
lunch ${MACHINE}-userdebug
make 2>&1 | tee build-log.txt

When the make command is complete, the build-log.txt file contains the execution output. Check for any errors.

# Create a bootable SD-card

* Issue these commands:

NOTE: This sample is for an 8G-card.

[source,console]
cd ${A}/out/target/product/${MACHINE}
sudo ./fsl-sdcard-partition.sh -c 7 -f ${SOC} /dev/sdX

# Boot from the SD-card

* `usm-imx8m-mini`
** Insert a created uSD card into the uSD socket `P23`
** Power on the board
** Press and hold `SW6` and `SW7`
** Release `SW6` and then `SW7`
